server:
    port: 8051

spring:
    application:
        name: awx-jwt-authenticator
    banner:
        location: banner.txt
    security:
      user:
          name: admin
          password: password

keycloak:
    auth-server-url: http://localhost:7080/auth
    realm: fabos
    resource: awx-jwt-authenticator
    credentials:
        secret: e7d227a2-df94-4f05-bf26-0f7053f836ca
    use-resource-role-mappings: false
    bearer-only: true

awx:
    host: localhost
    scheme: http
    port: 80
    username: awx-jwt-authenticator
    password: password
    organization-name: Service Lifecycle Management
    team-name: user

vault:
    scheme: http
    host: localhost
    port: 8200
    authentication: APPROLE
    token: s.t8H97SyHrPpHfLODxuIndeJ6
    app-role:
        app-role-path: approle
        role-id: awx-jwt-authenticator
        secret-id: ecefeb0e-0efe-a481-af52-6a136223614f
    kv-mount-path: awx-jwt-authenticator
